apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Yort.B4TTLE-ST4SY0N\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: recorddb
  name: recorddb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: recorddb
status:
  loadBalancer: {}
