apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Yort.B4TTLE-ST4SY0N\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: recordsservice
  name: recordsservice
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: recordsservice
status:
  loadBalancer: {}
